Logistic Regression:
  solver: saga
  penalty: elasticnet
  C: 1.0
  l1_ratio: 0
  max_iter: 4000
Neural Network:
  activation: tanh
  alpha: 0.01
  hidden_layer_sizes: [40, 60, 70, 100]
  learning_rate: adaptive
  max_iter: 1500
  solver: adam
Random Forest:
  bootstrap: true
  max_depth: 9
  max_features: sqrt
  min_samples_leaf: 1
  min_samples_split: 2
  n_estimators: 350
XGBOOST:
  colsample_bytree: 0.8
  gamma: 0.8
  learning_rate: 0.1
  max_depth: 7
  min_child_weight: 4
  n_estimators: 300
